# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: ingest.proto for package 'navi'

require 'grpc'
require_relative 'ingest_pb'

module Navi
  module IngestService
    # IngestService receives APM events from SDKs across all languages.
    # Auth: pass Bearer token via `authorization` metadata header.
    #       Pass project name via `x-project-name` metadata header.
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'navi.IngestService'

      # Ingest sends a batch of events in a single RPC call.
      rpc :Ingest, ::Navi::IngestRequest, ::Navi::IngestResponse
      # StreamIngest accepts a client-side stream of batches and flushes them
      # all before returning a single response. Useful for SDKs that queue
      # locally and replay on reconnect.
      rpc :StreamIngest, stream(::Navi::IngestRequest), ::Navi::IngestResponse
    end

    Stub = Service.rpc_stub_class
  end
end
